name: Workflow for DataDog example-javascript
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Install DataDog tracer
        run: npm install --save-dev dd-trace
      - name: Run tests and collect coverage
        run: npm run test
        shell: bash
        env:
          DD_CIVISIBILITY_AGENTLESS_ENABLED: true
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_SITE: datadoghq.eu
          NODE_OPTIONS: "-r dd-trace/ci/init"
